### PR TITLE
How to connect to postgres from laptop

### PR DESCRIPTION
**Pull request by heyvard**

### CODE REVIEW

**Comment by gorzan** [comment]
Accessing the db using the app credentials is not recommended from an audit standpoint. I would suggest your guide details how to create a personal user for the developer instead, and that you remove steps to extract app credentials.

**Comment by heyvard** [comment]
I agree, which is why I added the warning note https://github.com/nais/doc/pull/119/files#diff-e4d9e01101f97c32b57140914c49d2c6R158 

However when creating a postgres user in GCP, this user has no access to any tables, which is why you would need to connect using the app user to grant the new user read access. It is a chicken and egg problem.

It might be that I have overlooked something somewhere.

**Comment by x10an14** [comment]
I helped re-write some of the incompatible (old) GitBook syntaxes to the new mkdocs.

**Review by x10an14 — CHANGES_REQUESTED** [review]
Ref. https://github.com/nais/doc/pull/119#issuecomment-707121139, you must update your PR to not leverage the app credentials for this purpose.

EDIT: We would like to acknowledge that today there exist no solution that satisfies the above-mentioned demand. However, we're planning work ourselves on how to satisfactorily meet this requirement (meeting tomorrow already, poke #nais channel on Slack if you'd like to busy-poll).

**Comment by Kyrremann** [comment]
Lukker denne, da vi har fått lagd en bedre og sikrere løsning
https://github.com/nais/doc/pull/145

**Pull request closed without merging**
