### PR TITLE
Add reconnect workaround to the install guide

### PR DESCRIPTION
**Pull request by kjetiljd**

### CODE REVIEW

**Comment by x10an14** [comment]
I think it's best to move your text to an FAQ section - rather than as a sixth point on "Installation instructions" -section =)

Struggling to give you PR you could accept to the branch you've used as basis for your PR (meta - hehehe).
Discussing it with you in DM.

**Review by x10an14 — CHANGES_REQUESTED** [review]
https://github.com/nais/doc/pull/128#issuecomment-717103859

**Comment by kjetiljd** [comment]
I disagree, I think a FAQ section would be appropriate if this was rare, but a lot of people experience it. I consider the PR rejected, then.

**Comment by Sechmann** [comment]
I like this suggestion, this is a problem that usually only happens during first time install so adding it to the install guide makes sense. Could you reopen this @kjetiljd ?

**Comment by x10an14** [comment]
I see I committed my suggestion simultaneously you came with your comment @Sechmann.

Are you happy with https://github.com/nais/doc/commit/37af51eec8b1f0b84d3a1eac5f94b3edeab84781 ? =)

**Pull request closed without merging**
