### PR TITLE
Refurbish /nais-application/nais.yaml/reference page

### PR DESCRIPTION
**Pull request by x10an14**
1. Grouped similar specs into (by default) collapsed blocks.
2. Sorted some that were not listed in alphabetical order into alphabetical order.
3. Added vertical separators between each item/group.
4. Standardized "Example/Default/Allowed Values/Required" tags.

### CODE REVIEW

**Comment by Kyrremann** [comment]
Syns det blir for tungvindt å se på koden av disse endringene, når det er mest visuelt.

1. Uansett, fortsatt skeptisk til å bruke collapsed blocks, redd det kommer til å skjule mer enn det gir oversikt(?).
3. Vertikale linjer kan fungere bra tror jeg.
4. Og hva har du standardisert på med tags? Likte du ikke tykk skrift og tydelig linjeskift i kode og visuelt?

**Comment by Sechmann** [comment]
Needs preview to have meaningful opinion about the change.

I'm against if this interferes with CTRL+F

**Comment by x10an14** [comment]
> Needs preview to have meaningful opinion about the change.
> 
> I'm against if this interferes with CTRL+F

It does not interfere with CTRL+F for any search for any variable-length `p.q.r.s.t.u.v.w.x.y.z.` `nais.yaml` field/coordinate =)

**Comment by x10an14** [comment]
Force-merging this due to 5-6 thumbs-up on Slack, and only [one comment](https://github.com/nais/doc/pull/176#issuecomment-817687701) against - there's nothing technical stopping us from reverting this merge-commit later if feedback from developers/our customers is "This is awful".

**Pull request merged**
